<?php

/**
 * BaseJelvixNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $logo
 * @property string $text
 * 
 * @method string     getTitle() Returns the current record's "title" value
 * @method string     getLogo()  Returns the current record's "logo" value
 * @method string     getText()  Returns the current record's "text" value
 * @method JelvixNews setTitle() Sets the current record's "title" value
 * @method JelvixNews setLogo()  Sets the current record's "logo" value
 * @method JelvixNews setText()  Sets the current record's "text" value
 * 
 * @package    Jelvix
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJelvixNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jelvix_news');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}