<?php

/**
 * BaseJelvixNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property text $small_text
 * @property string $logo
 * @property string $text
 * @property boolean $is_active
 * 
 * @method string     getTitle()      Returns the current record's "title" value
 * @method text       getSmallText()  Returns the current record's "small_text" value
 * @method string     getLogo()       Returns the current record's "logo" value
 * @method string     getText()       Returns the current record's "text" value
 * @method boolean    getIsActive()   Returns the current record's "is_active" value
 * @method JelvixNews setTitle()      Sets the current record's "title" value
 * @method JelvixNews setSmallText()  Sets the current record's "small_text" value
 * @method JelvixNews setLogo()       Sets the current record's "logo" value
 * @method JelvixNews setText()       Sets the current record's "text" value
 * @method JelvixNews setIsActive()   Sets the current record's "is_active" value
 * 
 * @package    Jelvix
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJelvixNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jelvix_news');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('small_text', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}