jelvix_contacts:
  class: sfDoctrineRouteCollection
  options:
    model:                JelvixContacts
    module:               contacts
    prefix_path:          /contacts
    column:               id
    with_wildcard_routes: true

project_review_review:
  class: sfDoctrineRouteCollection
  options:
    model:                ProjectReview
    module:               review
    prefix_path:          /review
    column:               id
    with_wildcard_routes: true

project_review:
  class: sfDoctrineRouteCollection
  options:
    model:                ProjectReview
    module:               projects
    prefix_path:          /projects
    column:               id
    with_wildcard_routes: true

jelvix_projects:
  class: sfDoctrineRouteCollection
  options:
    model:                JelvixProjects
    module:               projects
    prefix_path:          /projects
    column:               id
    with_wildcard_routes: true

jelvix_services:
  class: sfDoctrineRouteCollection
  options:
    model:                JelvixServices
    module:               services
    prefix_path:          /services
    column:               id
    with_wildcard_routes: true

jelvix_news:
  class: sfDoctrineRouteCollection
  options:
    model:                JelvixNews
    module:               news
    prefix_path:          /news
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
