<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/08 22:45:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jelvix',
  'username' => 'root',
  'password' => 'kogeva89',
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_unicode_ci',
    'default_table_charset' => 'utf8',
  ),
  'name' => 'doctrine',
)),);
