<?php

/**
 * JelvixProjectCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JelvixProjectCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JelvixProjectCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JelvixProjectCategory');
    }
}