<?php

/**
 * JelvixStories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Jelvix
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JelvixStories extends BaseJelvixStories
{
    public function save(Doctrine_Connection $conn = null)
    {
        $this->setPhoto('/uploads/img/'.$this->getPhoto());
        parent::save($conn); // TODO: Change the autogenerated stub
    }
}
