<?php

/**
 * JelvixNewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JelvixNewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JelvixNewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JelvixNews');
    }
}