<?php

/**
 * JelvixServicesCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JelvixServicesCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JelvixServicesCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JelvixServicesCategory');
    }
}