<?php

/**
 * JelvixServicesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JelvixServicesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JelvixServicesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JelvixServices');
    }

    public static function getServicesOrderByCategoryName($name)
    {
        $q = Doctrine_Query::create()
            ->select()
            ->from('JelvixServices js')
            ->leftJoin('js.JelvixServicesCategory jsc')
            ->where('jsc.name = ?', $name);

        return $q->fetchArray();
    }
}