<?php

/**
 * ProjectReviewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectReviewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectReviewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectReview');
    }
}