# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

all:
  mails:
    contact:
      - kogeva19898@gmail.com
      - vovan5@yandex.ru
    request:
      - kogeva19898@gmail.com
      - vovan5@yandex.ru

  titles:
    main: Jelvix
    about: About
    services: Services
    projects: Projects
    stories: Stories
    news: News
    contacts: Contacts
    request: Request a quote

