# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

jelvix_news:
  url: /news
  class: sfDoctrineRouteCollection
  options:
    model: JelvixNews
    type: list
    actions: [show, list]
    module: news
    prefix_path: /news

jelvix_sevices:
  url: /services
  class: sfDoctrineRouteCollection
  options:
    model: JelvixServices
    type: list
    actions: [show, list]
    module: services
    prefix_path: /services

jelvix_services_filter:
  url: /services/filter-by-categoty
  param: { module: services, action: showServicesByCategory }

jelvix_projects:
  url: /projects
  class: sfDoctrineRouteCollection
  options:
    model: JelvixProjects
    type: list
    actions: [show, list]
    module: projects
    prefix_path: /projects

jelvix_projects_filter:
  url: /projects/filter-by-categoty
  param: { module: projects, action: showListByCategoty }

jelvix_about:
  url: /about
  param: { module: about, action: index }

jelvix_contacts:
  url: /contacts
  class: sfDoctrineRouteCollection
  options:
    model: JelvixContacts
    type: new
    actions: [new, create]
    module: contacts
    prefix_path: /contacts

jelvix_request:
  url: /request
  class: sfDoctrineRouteCollection
  options:
    model: JelvixRequest
    type: new
    actions: [new, create]
    module: request
    prefix_path: /request

jelvix_stories:
  url: /stories
  class: sfDoctrineRouteCollection
  options:
    model: JelvixStories
    type: list
    action: list
    module: stories
    prefix_path: /stories


# default rules
homepage:
  url:   /
  param: { module: main, action: index }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /
#  param: { action: index }
#
#default:
#  url:   /:module/:action/*
