generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JelvixProjects
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jelvix_projects
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [title, description]
      filter:  ~
      form:    ~
      edit:
        display: [category_id, title, thumbnail, photo, description, ios_link, android_link, other_link, created_at]
      new:
        display: [category_id, title, thumbnail, photo, description, ios_link, android_link, other_link, created_at]
