all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=jelvix'
      username: root
      password: kogeva89
      attributes:
        default_table_collate: utf8_unicode_ci
        default_table_charset: utf8