generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JelvixServices
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jelvix_services
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
         display: [title, text]
      filter:  ~
      form:    ~
      edit:
        display: [category_id, title, text]
      new:
        display: [category_id, title, text]
