JelvixNews:
  actAs:    { Timestampable: ~ }
  columns:
    title:  { type: string(255), notnull: true }
    logo:   { type: string(255) }
    text:   {type: string }

JelvixServices:
  actAs:         { Timestampable: ~ }
  columns:
    category_id: { type: integer, notnull: true }
    title:       { type: string(255), notnull: true }
    text:        {type: string }
  relations:
    JelvixServicesCategory:
      class: JelvixServicesCategory
      local: category_id
      foreign: id
      foreignAlias: JelvixServices
      foreignType: many
      type: one
      onDelete: CASCADE

JelvixServicesCategory:
  actAs:  { Timestampable: ~ }
  columns:
    name: { type: string(128), notnull: true }

JelvixProjects:
  actAs:  { Timestampable: ~ }
  columns:
    category_id:  { type: integer, notnull: true }
    title:        { type: string(255), notnull: true }
    thumbnail:    { type: string(255) }
    photo:        { type: string(255) }
    description:  { type: clob(16777215) }
    ios_link:     { type: string(255) }
    android_link: { type: string(255) }
    other_link:   { type: string(255) }
  relations:
      JelvixServicesCategory:
        class: JelvixProjectCategory
        local: category_id
        foreign: id
        foreignAlias: JelvixProjects
        foreignType: many
        type: one
        onDelete: CASCADE

JelvixProjectCategory:
  actAs:  { Timestampable: ~ }
  columns:
      name:       { type: string(255), notnull: true }