JelvixNews:
  actAs:    { Timestampable: ~ }
  columns:
    title:  { type: string(255), notnull: true }
    logo:   { type: string(255) }
    text:   {type: string }

JelvixServices:
  actAs:         { Timestampable: ~ }
  columns:
    category_id: { type: integer, notnull: true }
    title:       { type: string(255), notnull: true }
    text:        {type: string }
  relations:
    JelvixServicesCategory:
      class: JelvixServicesCategory
      local: category_id
      foreign: id
      foreignAlias: JelvixServices
      foreignType: many
      type: one
      onDelete: CASCADE

JelvixServicesCategory:
  actAs:  { Timestampable: ~ }
  columns:
    name: { type: string(128), notnull: true }

JelvixProjects:
  actAs:  { Timestampable: ~ }
  columns:
    category_id:  { type: integer, notnull: true }
    title:        { type: string(255), notnull: true }
    thumbnail:    { type: string(255) }
    photo:        { type: string(255) }
    description:  { type: clob(16777215) }
    ios_link:     { type: string(255) }
    android_link: { type: string(255) }
    other_link:   { type: string(255) }
  relations:
      JelvixServicesCategory:
        class: JelvixProjectCategory
        local: category_id
        foreign: id
        foreignAlias: JelvixProjects
        foreignType: many
        type: one
        onDelete: CASCADE

JelvixProjectCategory:
  actAs:  { Timestampable: ~ }
  columns:
      name:       { type: string(255), notnull: true }

ProjectReview:
  actAs:  { Timestampable: ~ }
  columns:
    project_id:   { type: integer }
    author:       { type: string, notnull: true }
    author_photo: { type: string(255) }
    text:         { type: string, notnull: true }
  relations:
    JelvixProjects:
      class: JelvixProjects
      local: project_id
      foreign: id
      foreignAlias: JelvixReview
      foreignType: many
      type: one
      onDelete: CASCADE

JelvixContacts:
  actAs:  { Timestampable: ~ }
  columns:
    name: { type: string(250), notnull: true }
    email_address: { type: string(250), notnull: true }
    subject: { type: string(250), notnull: true }
    message: { type: text, notnull: true }

JelvixRequest:
  actAs:  { Timestampable: ~ }
  columns:
    name: { type: string(250), notnull: true }
    email_address: { type: string(250), notnull: true }
    phone: { type: string(255), notnull: true }
    company: { type: string(250), notnull: true }
    message: { type: text }

JelvixStories:
  actAs:  { Timestampable: ~ }
  columns:
    author:   { type: string(250), notnull: true }
    photo:    { type: string(250), notnull: true }
    position: { type: string(250), notnull: true }
    text:     { type: text, notnull: true }