generator:
  class: sfDoctrineGenerator
  param:
    model_class:           jelvixRequest
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jelvix_request
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, email_address, phone,company]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
